workflows_repository: global-actions-workflows # The repository where your organization workflows are defined. (default: .github)
include_workflows_repository: false # Whether to run these checks for the central workflows_repository. (default: false)
exclude:
  repositories: # Repositories that are excluded and should not trigger organization workflows. Accepts wildcards. (default: [])
  - k8s-resources
  - k8s-automation
  - helm-charts
  - keycloak-configuration
  - spoiler
  - deployments
